### ISSUE TITLE
dropbox.exceptions.BadInputError: BadInputError('xxxxxxxxx', 'Error in call to API function "files/upload": Your app is not permitted to access this endpoint because it does not have the required scope \'files.content.write\'. The owner of the app can enable the scope for the app using the Permissions tab on the App Console.')

### ISSUE THREAD

**Issue by jh-yi** [WilmerWang/autoLiterature#3]
你好，我按步骤配置了dropbox，但是依旧收到权限错误
dropbox.exceptions.BadInputError: BadInputError('xxxxxxxxx', 'Error in call to API function "files/upload": Your app is not permitted to access this endpoint because it does not have the required scope \'files.content.write\'. The owner of the app can enable the scope for the app using the Permissions tab on the App Console.')

**Comment by wilmerwang** [comment]
@jh-yi 你好，这个问题很大可能是因为你先生成了密钥，然后又开的权限；建议你确定权限打开之后，再返回来生产密钥。

**Comment by jh-yi** [comment]
> @jh-yi 你好，这个问题很大可能是因为你先生成了密钥，然后又开的权限；建议你确定权限打开之后，再返回来生产密钥。

我确定是按步骤先开权限再生成token的

**Comment by wilmerwang** [comment]
@jh-yi 你开完权限后点保存，然后刷新页面，确定权限是对的，再生成密钥试试。
问题肯定在（设置权限-->生成永久密钥）部分

**Comment by jh-yi** [comment]
Problem solved! 非常感谢
