### ISSUE TITLE
INFO:Sci-Hub:Failed to fetch pdf with identifier 10.1038/s41598-021-92475-7 (resolved url None) due to request exception.

### ISSUE THREAD

**Issue by 4fee8fea** [WilmerWang/autoLiterature#5]
感谢您分享的脚本！

目前我这里配置了proxychains4，经`proxychains4 wget https://www.google.com`测试，显示`connected`，linux终端的代理应该已经设置好了。

在使用命令`proxychains4 python main.py -p * -k * -t 1`开始该脚本之后：

在.md笔记中输入`- [10.1038/s41598-021-92475-7]`，得到如下结果：

1.终端：
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  api.crossref.org:80  ...  OK
INFO:Sci-Hub:Failed to fetch pdf with identifier 10.1038/s41598-021-92475-7 (resolved url None) due to request exception.

2.md笔记:
![bug](https://user-images.githubusercontent.com/53552367/132307396-d22e2061-111b-43bb-96ab-a6d224e55c4b.png)
在`publisher`和`pdf`处将会显示`Please manually add the attachment link`

请问这可能是什么原因导致的呢？（尝试了另外4个DOI号，也出现了同样的问题。）

感谢解答，祝好！

**Comment by 4fee8fea** [comment]
猜测可能是验证码的问题。基于这种猜测，我尝试修改了modules.py中的`_get_available_scihub_urls()`函数。

```python
def _get_available_scihub_urls(self):
    urls = []
    res = requests.get('https://sci-hub.now.sh/')
    s = self._get_soup(res.content)
    for a in s.find_all('a', href=True):
        if 'sci-hub.se' in a['href']:
            urls.append(a['href'])
    return urls
```

改动部分在`if "sci-hub" in a["href"]:` -> `if "sci-hub.se" in a["href"]:`

这样改动是因为我本地访问`sci-hub.se`、输入DOI后下载文献不需要输入验证码。

但这种改动并不奏效。也许是脚本下载的时候sci-hub会要求输入验证码？

抛砖引玉，求作者指点

**Comment by wilmerwang** [comment]
> 感谢您分享的脚本！
> 
> 目前我这里配置了proxychains4，经`proxychains4 wget https://www.google.com`测试，显示`connected`，linux终端的代理应该已经设置好了。
> 
> 在使用命令`proxychains4 python main.py -p * -k * -t 1`开始该脚本之后：
> 
> 在.md笔记中输入`- [10.1038/s41598-021-92475-7]`，得到如下结果：
> 
> 1.终端：
> [proxychains] Strict chain ... 127.0.0.1:1080 ... api.crossref.org:80 ... OK
> INFO:Sci-Hub:Failed to fetch pdf with identifier 10.1038/s41598-021-92475-7 (resolved url None) due to request exception.
> 
> 2.md笔记:
> ![bug](https://user-images.githubusercontent.com/53552367/132307396-d22e2061-111b-43bb-96ab-a6d224e55c4b.png)
> 在`publisher`和`pdf`处将会显示`Please manually add the attachment link`
> 
> 请问这可能是什么原因导致的呢？（尝试了另外4个DOI号，也出现了同样的问题。）
> 
> 感谢解答，祝好！

感谢你提出这个问题，大部分sci-hub的嵌入label为‘ifram’，因此代码中仅仅查找了‘ifram’。但是目前有一些嵌入label变为了‘embed’，因此会出现查询不到嵌入pdf路径的问题。我添加了embed标签，目前已解决了该问题
