### ISSUE TITLE
为啥会这样子的呢？

### ISSUE THREAD

**Issue by Gary-code** [WilmerWang/autoLiterature#9]
![图片](https://user-images.githubusercontent.com/56477815/148727149-6c0254d0-e0c9-4388-9e62-8ce1bb245ebf.png)

**Comment by wilmerwang** [comment]
@Gary-code 
你好，有两个参数我忘了写在README文件，现在已经加上，你可以使用下面的命令，其中-p是你写笔记的文件夹路径，-k是dropbox token
```
python scr/autosync.py -p ../note -k your_access_token
```

**Comment by Gary-code** [comment]
> @Gary-code 你好，有两个参数我忘了写在README文件，现在已经加上，你可以使用下面的命令，其中-p是你写笔记的文件夹路径，-k是dropbox token
> 
> ```
> python scr/autosync.py -p ../note -k your_access_token
> ```

thank you so much
